"""Talk to OpenSSH: resolve, render, and validate config."""

from __future__ import annotations

import contextlib
import os
import subprocess
import tempfile
from typing import Any

from .naming import normalize_host
from .paths import conf_dir, learned_file
from .store import atomic_write, backup_file

UNSAFE_OR_TEMPORARY_OPTIONS = {
    "proxycommand",
    "localforward",
    "remoteforward",
    "dynamicforward",
    "certificatefile",
    "pkcs11provider",
    "securitykeyprovider",
    "remotecommand",
    "localcommand",
}


def parse_ssh_g(output: str) -> dict[str, Any]:
    values: dict[str, Any] = {}
    identities: list[str] = []

    for raw_line in output.splitlines():
        if not raw_line.strip():
            continue

        try:
            key, value = raw_line.split(None, 1)
        except ValueError:
            continue

        key = key.lower()
        value = value.strip()

        if key in UNSAFE_OR_TEMPORARY_OPTIONS:
            continue

        if key == "identityfile":
            if value and value.lower() != "none":
                identities.append(value)
            continue

        if key in {"hostname", "user", "port", "proxyjump"}:
            values[key] = value

    if identities:
        values["identityfile"] = identities

    return values


def get_effective_config(
    destination: str,
    ssh_args: list[str],
) -> dict[str, Any]:
    result = subprocess.run(
        ["ssh", "-G", *ssh_args, destination],
        text=True,
        capture_output=True,
        check=False,
    )

    if result.returncode != 0:
        raise RuntimeError(result.stderr.strip() or "ssh -G failed")

    config = parse_ssh_g(result.stdout)
    config.setdefault("hostname", normalize_host(destination))

    if "@" in destination and not config.get("user"):
        config["user"] = destination.rsplit("@", 1)[0]

    return config


def render_config(metadata: dict[str, Any]) -> str:
    lines = [
        "# Automatically generated by ssh-learn.",
        "# Edit entries using ssh-learn commands instead of editing this file.",
        "",
    ]

    for alias_name in sorted(metadata.get("hosts", {})):
        entry = metadata["hosts"][alias_name]
        hostname = entry.get("hostname")

        if not hostname:
            continue

        tags = entry.get("tags", [])
        lines.append(f"# Tags: {' '.join(tags) if tags else 'none'}")
        lines.append(f"# Last used: {entry.get('last_used', '')}")
        lines.append(f"# Successful sessions: {int(entry.get('count', 0))}")
        lines.append(f"Host {alias_name}")
        lines.append(f"    HostName {hostname}")

        if entry.get("user"):
            lines.append(f"    User {entry['user']}")

        port = str(entry.get("port") or "22")
        if port != "22":
            lines.append(f"    Port {port}")

        proxyjump = entry.get("proxyjump")
        if proxyjump and str(proxyjump).lower() != "none":
            lines.append(f"    ProxyJump {proxyjump}")

        for identity in entry.get("identityfiles", []):
            if identity and str(identity).lower() != "none":
                lines.append(f"    IdentityFile {identity}")

        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def validate_generated_config(config_text: str, aliases: list[str]) -> None:
    # ssh parses the whole file even when resolving a single host, so one
    # `ssh -G` run is enough to catch any syntax error in the rendered config.
    fd, tmp_name = tempfile.mkstemp(
        prefix="learned.",
        suffix=".conf",
        dir=conf_dir(),
    )

    probe = aliases[0] if aliases else "localhost"

    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(config_text)

        os.chmod(tmp_name, 0o600)

        result = subprocess.run(
            ["ssh", "-G", "-F", tmp_name, probe],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.PIPE,
            text=True,
            check=False,
        )

        if result.returncode != 0:
            raise RuntimeError(
                result.stderr.strip() or "SSH config validation failed"
            )
    finally:
        with contextlib.suppress(OSError):
            os.unlink(tmp_name)


def write_learned_config(metadata: dict[str, Any]) -> None:
    config_text = render_config(metadata)
    aliases = sorted(metadata.get("hosts", {}))
    validate_generated_config(config_text, aliases)
    backup_file(learned_file(), "learned")
    atomic_write(learned_file(), config_text)

